# This rule is not used by the project routines itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over routines.a2d2.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: routines
    app.kubernetes.io/managed-by: kustomize
  name: scheduletrigger-admin-role
rules:
- apiGroups:
  - routines.a2d2.dev
  resources:
  - scheduletriggers
  verbs:
  - '*'
- apiGroups:
  - routines.a2d2.dev
  resources:
  - scheduletriggers/status
  verbs:
  - get
